main.textContent = "테스트";
main.style.fontSize = "200px";
const tempData = [
  {
    index: 1,
    subject: "첫번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김첨지",
  },
  {
    index: 2,
    subject: "두번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김흥도",
  },
  {
    index: 3,
    subject: "세번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김삿갓",
  },
  {
    index: 4,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 5,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 6,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 7,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 8,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 9,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 10,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 11,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 12,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 13,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 14,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 15,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 16,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 17,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 18,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 19,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 20,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 21,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 22,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 23,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
  {
    index: 24,
    subject: "네번째 글",
    content: "로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 로렘 ",
    name: "김폭도",
  },
];
